Mox.defmock(WeatherStation.People.RolodexMock, for: WeatherStation.People.Rolodex)
Mox.defmock(External.DockYard.ApiMock, for: External.DockYard.Api)
Mox.defmock(WeatherStation.Weather.ApiMock, for: WeatherStation.Weather.Api)
ExUnit.start()
ExUnit.configure(exclude: [:external])
